export { default as About } from './About/About';
export { default as Comparison } from './Comparison/Comparison';
export { default as Contact } from './Contact/Contact';
export { default as Detail } from './Detail/Detail';
export { default as Filter } from './Filter/Filter';
export { default as Home } from './Home/Home';
export { default as How } from './How/How';
export { default as NotFound } from './NotFound/NotFound';
export { default as SchoolPreview } from './SchoolPreview/SchoolPreview';
